[tcpout]
defaultGroup = splunk_indexer

[tcpout:splunk_indexer]
server = <SPLUNK_SERVER_IP>:9997        //server = 192.168.213.132

[tcpout-server://<SPLUNK_SERVER_IP>:9997]    //tcpout-server://192.168.213.132:9997
